---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-controllers # change here
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers # and here
  prune: true
  wait: true
# add the following
  patches:
  - patch: |
      - op: replace
        path: /spec/values/ingress/hosts/0/host
        value: "dashboard.production"
    target:
      kind: HelmRelease
      name: ww-gitops